#!/bin/bash
set -e  # To exit on the first error

PROJECT_ROOT="/content/drive/MyDrive/Colab Notebooks/M2 MVA/Algorithms for Speech and NLP/Project/espnet-speech_mva"
#DATA_ROOT="${PROJECT_ROOT}/data/subset_for_testing_4"
#DATA_ROOT_NO_SPACES="/content/ml_superb_data"
DATA_ROOT="/content/domains_asr_dataset"
#ln -sfn "${DATA_ROOT}" "${DATA_ROOT_NO_SPACES}"
LOCAL_PROJECT_ROOT=/content
ESPNET_DIR="${LOCAL_PROJECT_ROOT}/espnet-speech_mva/espnet"
S3PRL_DIR="${LOCAL_PROJECT_ROOT}/espnet-speech_mva/s3prl"
SCTK_DIR="${LOCAL_PROJECT_ROOT}/espnet-speech_mva/lib/SCTK"
ENV_FILE="$(dirname "${PROJECT_ROOT}")/colab_env.sh"

echo "# Auto-generated by colab_setup.sh" > "${ENV_FILE}"

INSTALL_FLASH_ATTN=false
INSTALL_SCLITE=true
FIX_TORCH_VERSION=true
INSTALL_WANDB=true

echo "============================================"
echo " [1/5] Installing system packages"
echo "============================================"
sudo apt-get update
sudo apt-get install -y sox libsox-fmt-all screen

echo "============================================"
echo " [2/5] Installing Python packages"
echo "============================================"

# We downgrade a few packages if needed
if [ "$FIX_TORCH_VERSION" = true ]; then
    echo "  -> Pinning torch and torchaudio to 2.4.0, torchvision to 0.19.0, and transformers to 4.44.0"
    pip install torch==2.4.0 torchaudio==2.4.0 torchvision==0.19.0 transformers==4.44.0
fi

# We install espnet and s3prl in editable mode
if [ ! -d "${LOCAL_PROJECT_ROOT}/espnet-speech_mva" ]; then
    git clone https://github.com/rodrigo-paganini/espnet-speech_mva.git "${LOCAL_PROJECT_ROOT}/espnet-speech_mva"
else
    echo "  -> espnet-speech_mva already exists, skipping clone"
fi

if [ ! -d "$S3PRL_DIR" ]; then
    git clone -b main https://github.com/s3prl/s3prl.git $S3PRL_DIR
else
    echo "  -> s3prl already exists, skipping clone"
fi
cp -f "$(dirname "${PROJECT_ROOT}")/data_prep.py" "${ESPNET_DIR}/egs2/ml_superb/asr1/local/"
pip install -e $ESPNET_DIR
pip install -e $S3PRL_DIR

#pip install -e "${ESPNET_DIR}"
#pip install -e "${S3PRL_DIR}"

# We make fix_data_dir.sh executable
chmod +x "$ESPNET_DIR/egs2/ml_superb/asr1/utils/fix_data_dir.sh"

# Editing db.sh to set MLSUPERB path
echo "  -> Setting MLSUPERB in db.sh to ${DATA_ROOT}"
sed -i "s|^MLSUPERB=.*|MLSUPERB=${DATA_ROOT}|" "${ESPNET_DIR}/egs2/ml_superb/asr1/db.sh"

# Removing dev set from test_sets in run_multi.sh to only score on test set
echo "  -> Removing dev set from test_sets in run_multi.sh"
sed -i 's/test_set="${train_dev} test_${duration}${suffix}"/test_set="test_${duration}${suffix}"/' "${ESPNET_DIR}/egs2/ml_superb/asr1/run_multi.sh"

echo "  -> Setting inference_nj=8"
sed -i 's/^inference_nj=4/inference_nj=8/' "${ESPNET_DIR}/egs2/ml_superb/asr1/run_multi.sh"

sed -i 's/^gpu_inference=true/gpu_inference=false/' "${ESPNET_DIR}/egs2/ml_superb/asr1/run_multi.sh"

pip install resampy

pip install git+https://github.com/microsoft/LoRA

pip install soundfile huggingface_hub

echo "============================================"
echo " [3/5] Optional: Flash Attention"
echo "============================================"
if [ "$INSTALL_FLASH_ATTN" = true ]; then
    echo "  -> Building flash_attn (this will take a while...)"
    pip install flash_attn --no-build-isolation
else
    echo "  -> Skipped (set INSTALL_FLASH_ATTN=true to enable)"
fi

echo "============================================"
echo " [4/5] Optional: sclite (SCTK)"
echo "============================================"
if [ "$INSTALL_SCLITE" = true ]; then
    if [ ! -d "${SCTK_DIR}" ]; then
        echo "  -> Cloning SCTK repository to ${SCTK_DIR}"
        mkdir -p "${LOCAL_PROJECT_ROOT}/espnet-speech_mva/lib"
        git clone https://github.com/usnistgov/SCTK.git "${SCTK_DIR}"
    fi
    echo "  -> Building sclite"
    cd "${SCTK_DIR}"
    make config
    make all
    make install
    export PATH="${SCTK_DIR}/bin:$PATH"
    echo "export PATH=${SCTK_DIR}/bin:\$PATH" >> "${ENV_FILE}"
    echo "  -> sclite location: $(which sclite)"
else
    echo "  -> Skipped (set INSTALL_SCLITE=true to enable)"
fi

echo "============================================"
echo " [5/5] Optional: Weights & Biases"
echo "============================================"
if [ "$INSTALL_WANDB" = true ]; then
    pip install wandb editdistance
    echo "  -> Installed. Run 'wandb login' manually to authenticate."
else
    echo "  -> Skipped (set INSTALL_WANDB=true to enable)"
fi

# Adding sclite to PATH for this session (even if pre-built from a prior run)
if [ -d "${SCTK_DIR}/bin" ]; then
    export PATH="${SCTK_DIR}/bin:$PATH"
    # We ensure env file does not have the entry to avoid duplicates
    if ! grep -q "SCTK" "${ENV_FILE}" 2>/dev/null; then
        echo "export PATH=${SCTK_DIR}/bin:\$PATH" >> "${ENV_FILE}"
    fi
fi

echo ""
echo "============================================"
echo " Setup complete!"
echo "============================================"
echo " espnet dir : ${ESPNET_DIR}"
echo " s3prl dir  : ${S3PRL_DIR}"
echo " env file   : ${ENV_FILE}"
echo ""
echo " Remember to set MLSUPERB in db.sh to point"
echo " to your data folder before running experiments."
echo "============================================"
